// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reviews.Models;

namespace Reviews.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reviews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, Name = "Representation" },
                        new { Id = 2, Name = "Animal Description" }
                    );
                });

            modelBuilder.Entity("Reviews.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<string>("ImageURL");

                    b.Property<string>("ReviewCategory");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new { Id = 1, CategoryId = 1, Content = "Wolf is a symbol of guardianship, ritual, loyalty, and spirit. Wolf has the ability to make quick and firm emotional attachments, and often need to trust their own instincts. Thus they teach us to do the same, to trust our hearts and minds, and have control over our own lives.", ImageURL = "https://i.pinimg.com/originals/dd/7c/33/dd7c33afca6b9ab815b944fbc5fbfc33.jpg", ReviewCategory = "Representation", Title = "Wolf" },
                        new { Id = 2, CategoryId = 1, Content = "Owls live within the darkness, which includes magic, mystery, and ancient knowledge. Related to the night is the moon, which owls are also connected to. It becomes a symbol of the feminine and fertility, with the moon's cycles of renewal. Even the mythology relates owl to this wisdom and femininity.", ImageURL = "https://i1.sndcdn.com/avatars-000313148980-h2uglx-t500x500.jpg", ReviewCategory = "Representation", Title = "Owl" },
                        new { Id = 3, CategoryId = 1, Content = "It is usually believed that the crow is a symbol of bad luck and death, but it is not always the case. A crow may be a symbol of life magic and mysteries. It also symbolizes intelligence, flexibility and destiny.", ImageURL = "https://a0.35photo.ru/photos_col/r2/97/487882_500r.jpg", ReviewCategory = "Representation", Title = "Crow" }
                    );
                });

            modelBuilder.Entity("Reviews.Models.Review", b =>
                {
                    b.HasOne("Reviews.Models.Category", "Category")
                        .WithMany("Reviews")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
